---
author: "Noreen Mayat" 
title: "ASCVD_data"
output: html_document
date: "2024-02-29"
---

```{r, setup, include=FALSE}
# Load in Libraries
library(NHANES)
library(dplyr)
library(haven)
library(tidyverse)
library(caret)
library(tidymodels)
library(tidyverse)
library(readr)
library(corrplot)
library(CVrisk)

# For Imputing
library(mice)
library(missForest)
library(VIM)
library(softImpute)
library(ggplot2)

# Set appropriate root directory 
# knitr::opts_knit$set(root.dir = '/Users/noreenmayat/Desktop/Github/Machine-Learning-to-Predict-Cardiovascular-Health-Outcomes/Data Cleaning Files')
```

### Load Data

```{r}
# Load in Data
df_11_12 <- read.csv("Cleaned Data/11_12_cleaned.csv")
df_11_12$Year <- c(1)

df_13_14 <- read.csv("Cleaned Data/13_14_cleaned.csv")
df_13_14$Year <- c(2)

df_15_16 <- read.csv("Cleaned Data/15_16_cleaned.csv")
df_15_16$Year <- c(3)

df_17_18 <- read.csv("Cleaned Data/17_18_cleaned.csv")
df_17_18$Year <- c(4)
```

### Combine Data

```{r}
# Combine all Data
full_df <- bind_rows(df_11_12, df_13_14, df_15_16, df_17_18)

full_df$X <- NULL
full_df$HeartAttack <- NULL
full_df$Stroke <- NULL
full_df$CoronaryDisease <- NULL
full_df$HeartFailure <- NULL
```

```{r}
# Factoring the outcome/target variable
full_df$NegOutcome <- factor(full_df$NegOutcome, levels = c(0, 1))
```

### Counting NAs

```{r}
# Count NAs each column
na_counts <- colSums(is.na(full_df))
print(na_counts)

# Barplot showing null values 
# Convert to dataframe for plotting
na_data <- as.data.frame(na_counts)
na_data$Column <- rownames(na_data)
names(na_data) <- c("NA_Count", "Column")

ggplot(na_data, aes(x = reorder(Column, NA_Count), y = NA_Count)) +
  geom_bar(stat = "identity", fill = "tomato") +
  theme_minimal() +
  labs(title = "Missing Values in Each Column", x = "Column", y = "Number of Missing Values") +
  coord_flip() # Use coord_flip() to make the plot horizontal
```

**Plotting the target/response feature in the dataset:**
```{r echo=FALSE, warning = FALSE, message = FALSE}
## Plotting the target feature 
ggplot(full_df, aes(x = NegOutcome)) + 
  geom_bar(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Target Feature: Negative CVD Outcome", x = "Negative CVD Outcome", y = "Count") +
  theme_minimal()

# Count of each: approvals vs. denials 
count_table <- table(full_df$NegOutcome, exclude=NULL)
print(count_table)

# Calculate the percentage for each category
percentages <- prop.table(count_table) * 100
print(percentages)

# Count of each: approvals vs. denials 
count_table <- table(full_df$NegOutcome)
print(count_table)

# Calculate the percentage for each category
percentages <- prop.table(count_table) * 100
print(percentages)
```

```{r}
# Checking for near zero variances
nearZeroVar(full_df, saveMetrics = TRUE)   # all metrics
```

```{r}
# Splitting the Data
set.seed(1)
split <- initial_split(full_df, prop = 0.75, strata = "NegOutcome") 
# 75%-25% split

df_train <- training(split)
df_test <- testing(split)
```

**Plotting the target/response feature in the training dataset:**
```{r echo=FALSE, warning = FALSE, message = FALSE}
## Plotting the target feature 
ggplot(df_train, aes(x = NegOutcome)) + 
  geom_bar(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Target Feature: Training", x = "Negative CVD Outcome", y = "Count") +
  theme_minimal()

# Count of each: approvals vs. denials 
count_table_train <- table(df_train$NegOutcome, exclude=NULL)
print(count_table_train)

# Calculate the percentage for each category
percentages_train <- prop.table(count_table_train) * 100
print(percentages_train)

# Count of each: approvals vs. denials 
count_table <- table(df_train$NegOutcome)
print(count_table)

# Calculate the percentage for each category
percentages <- prop.table(count_table) * 100
print(percentages)
```

**Plotting the target/response feature in the testing dataset:**
```{r echo=FALSE, warning = FALSE, message = FALSE}
## Plotting the target feature 
ggplot(df_test, aes(x = NegOutcome)) + 
  geom_bar(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Target Feature: Testing", x = "Negative CVD Outcome", y = "Count") +
  theme_minimal()

# Count of each: approvals vs. denials 
count_table_test <- table(df_test$NegOutcome, exclude=NULL)
print(count_table_test)

# Calculate the percentage for each category
percentages_test <- prop.table(count_table_test) * 100
print(percentages_test)

# Count of each: approvals vs. denials 
count_table <- table(df_test$NegOutcome)
print(count_table)

# Calculate the percentage for each category
percentages <- prop.table(count_table) * 100
print(percentages)
```
### Imputing Data

```{r, results='hide'}
# Impute Rest of Missing Data 
imputation_fun_mice <- function(df, target){
  init <- mice(df, maxit=0, remove.collinear = FALSE, remove.constant = FALSE) 
  
  # Ensure the target variable is not imputed 
  init$method[target] <- ""
  init$predictorMatrix[, target] <- 0
  
  imputed <- mice(df, method=init$method, predictorMatrix=init$predictorMatrix, m=5, nnet.MaxNWts = 5000, remove.collinear = FALSE, remove.constant = FALSE)
  completed <- mice::complete(imputed)
  return(completed)
}

imputed_train <- imputation_fun_mice(df_train, "NegOutcome")
imputed_test <- imputation_fun_mice(df_test, "NegOutcome")
```

```{r}
# Count NAs each column to make sure imputation worked
colSums(is.na(imputed_train))
colSums(is.na(imputed_test))
```

```{r}
column_types <- sapply(imputed_train, class)
print(column_types)
```

### Compute ASCVD scores for training and testing sets
```{r, warning=FALSE}
# Applying the function to every row for specified columns
results_train <- apply(imputed_train[, c("Race1", "Sex", "Age", "TotalChol", "HDLChol", "AvgSysBP", "BPMed", "Smoking", "Diabetes")], 1, function(row) ascvd_10y_accaha(row[1], row[2], as.numeric(row[3]), as.numeric(row[4]), as.numeric(row[5]), as.numeric(row[6]), as.numeric(row[7]), as.numeric(row[8]), as.numeric(row[9])))

results_test <- apply(imputed_test[, c("Race1", "Sex", "Age", "TotalChol", "HDLChol", "AvgSysBP", "BPMed", "Smoking", "Diabetes")], 1, function(row) ascvd_10y_accaha(row[1], row[2], as.numeric(row[3]), as.numeric(row[4]), as.numeric(row[5]), as.numeric(row[6]), as.numeric(row[7]), as.numeric(row[8]), as.numeric(row[9])))

# Note that ASCVD risk score can only be calculated for individuals between age range 20-79

# Adding the result as a new column to the DataFrames
imputed_train$ASCVD <- results_train
imputed_test$ASCVD <- results_test

# Combine dataframes
full_df_cleaned <- rbind(imputed_train, imputed_test)
```


```{r}
# Saving CSVs
write.csv(imputed_train, "Cleaned Data/imputed_train.csv")
write.csv(imputed_test, "Cleaned Data/imputed_test.csv")
write.csv(full_df_cleaned, "Cleaned Data/imputed_full.csv")
```




